### ISSUE TITLE
version 0.2.1 has a breaking change

### ISSUE THREAD

**Issue by mockersf** [chinedufn/rectangle-pack#3]
Thank you for this library!

This issue is just to mention that 0.2.1 has a breaking change, as the `pack_rects` method changed to take an `&mut`

**Comment by mockersf** [comment]
version 0.2.1 also break released version of Bevy 0.3 and 0.4 😢

**Comment by chinedufn** [comment]
I'm very sorry for this. Responded here -> https://github.com/bevyengine/bevy/pull/1741

If it helps. I can put out a `0.2.2` that reverts this.

Then publish a `0.3.0` that re-applies the breaking change. Then you can update `bevy_sprite` to use 0.2.2 and I think that would fix the downstream crates?

Let me know if that works for you.

**Comment by cart** [comment]
I think that publishing a 0.2.2 version that reverts is the right call. Otherwise we'll need to patch all of our previous releases.

**Comment by chinedufn** [comment]
Awesome thanks a lot for confirming.

0.2.2 and 0.3.0 have been published.

**Comment by chinedufn** [comment]
Here's 0.2.2's commit -> https://github.com/chinedufn/rectangle-pack/commit/a1c39084639ec993a25bce4150936ef61d3848d7

**Comment by cart** [comment]
Thanks!
